### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vnikale** [ajchaudhari/WRIST-segmentation#1]
Hello.
I am getting an error while installing the module into 3D Slicer. In "Module Finder" WRIST is highlighted red and there is a note "WRIST module is not loaded". In the Python console of 3D slicer I am getting the following message:
 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hash\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Python\Lib\imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:/WRIST-segmentation-master/WRIST.py", line 453
    def onDiffusionItsSliderChange(self,newValue):
                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```
![image](https://user-images.githubusercontent.com/11405938/115035459-4521d580-9ed5-11eb-9a25-db224b3e93e4.png)

**Comment by OperaRuss** [comment]
Chiming in from April 2022.  Problem was encountered on a Windows 10 installation.  Attempting to run the script in a python terminal returns the "inconsistent tabs and spaces" error above.  I attempted to use the Unix 'expand' command from within Windows Subsystem for Linux and it ran to completion, so should have replaced all tabs with four spaces.  This did not resolve the issue.

**Comment by Amaupac** [comment]
Sadly I think this no longer works and the project is inactive.
